#create input distributions
weather_file<- rep(paste(pwc_weather_used, sep = ""), Nsims)
sim_start<- rep(paste(simstart, sep = ""), Nsims)
sim_end<- rep(paste(simend, sep = ""), Nsims)
inputdf<- data.frame(weather_file, sim_start, sim_end)
#create PRZM input df and putting the input in the io directory 
inputdf <- cbind(inputdf, PFAC)
inputdf <- cbind(inputdf, uslek)
inputdf <- cbind(inputdf, uslels)
inputdf <- cbind(inputdf, uslep)
inputdf <- cbind(inputdf, CN)
inputdf <- cbind(inputdf, depth)
inputdf <- cbind(inputdf, uslec)
inputdf <- cbind(inputdf, bd1)
inputdf <- cbind(inputdf, bd2)
inputdf <- cbind(inputdf, bd3)
inputdf <- cbind(inputdf, bd4)
inputdf <- cbind(inputdf, bd5)
inputdf <- cbind(inputdf, dep)
inputdf <- cbind(inputdf, benthic_depth)
inputdf <- cbind(inputdf, porosity)
inputdf <- cbind(inputdf, bulk_density)
inputdf <- cbind(inputdf, FROC2)
inputdf <- cbind(inputdf, DOC2)
inputdf <- cbind(inputdf, BNMAS)
inputdf <- cbind(inputdf, SUSED)
inputdf <- cbind(inputdf, CHL)
inputdf <- cbind(inputdf, FROC1)
inputdf <- cbind(inputdf, DOC1)
inputdf <- cbind(inputdf, PLMAS)
write.csv(inputdf, file = paste(pwcdir, "io/inputdata_przm_vvwm.csv", sep = ""))

